ckpt_strict: True
exp_name: TEST
trainer: delta
seed: 42
optim: Adam
sub_iter: 0
time_delay: 0
save_folder: result/save_model/
save_log: result/save_log/
lr_adjust: fix
debug: False
sub_iter: 0
weight_decay: 0.0005
gamma: 0.1
momentum: 0.9
start_iter: 0
mix: False
train_batch_size: 16
val_batch_size: 16
display_freq: 20
use_amp: False
use_amp_in_eval: False 
load_optim: True